# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/application-properties.html#application-properties
# ===================================================================

# ===================================================================
# Application specific properties
# ===================================================================
